---
title: "Untitled"
author: "Mansi"
date: "Saturday, November 19, 2016"
output: pdf_document
---

## Libraries ##


library(stargazer)  # for summary statistics and regression tables
library(magrittr)  # for 'piping': more readable code
library(ggplot2)  # the ggplot2 package provides nice function for plotting
library(arm)  # for the sim() function to simulate model estimates
library(interplot)  # for plotting interactions
library(dplyr)  # for data manipulation

library(foreign)

## Reading 2014 dataset into an object
x <- read.dta("C:/Users/hp/Downloads/ESS7e02.dta")

## Subsetting x to keep only the youth
x <- subset(x, x$agea <= 25 & x$agea >= 18)

## Capturing the variable names of d into a vector and subsetting
df_vars <- c()
df_vars <- names(ESSData[1:26])

x_vars <- names(x)

## Checking for common variables

common <- intersect(x_vars, df_vars)
common

remain <- setdiff(df_vars, x_vars)
remain ## Shows variables in the dataset until 2012 but not in 2014

## Dropping irrelevant variables
x <- x[ ,common]

## Removing Undesired Countries from ESS Dataset ##
temp <- with(x, which(x$cntry == "AT" | x$cntry == "LT" | x$cntry == "IL" | x$cntry == "CH", arr.ind=TRUE))

x <- x[-temp, ]

## Removing unwanted columns from x using the vector ESSVariables created in Data cleaning
temp2 <- intersect(ESSVariables, common) #Since common refers to variables in x

setdiff(ESSVariables, common)
setdiff(common, ESSVariables)

x2 <- x[temp2]


## Recoding variables in x2 which is the shredded down 2014 dataset ##
table(x2$polintr)
x2$polintr <- as.numeric(as.factor(x2$polintr)) 
table(x2$polintr) ## This has the numbers representing categories now

x2$vote <- as.integer(as.factor(x2$vote))
x2$contplt <- as.integer(as.factor(x2$contplt))
x2$wrkprty <- as.integer(as.factor(x2$wrkprty))
x2$wrkorg <- as.integer(as.factor(x2$wrkorg))
x2$badge <- as.integer(as.factor(x2$badge))
x2$sgnptit <- as.integer(as.factor(x2$sgnptit))
x2$ pbldmn <- as.integer(as.factor(x2$pbldmn))
x2$bctprd <- as.integer(as.factor(x2$bctprd))
x2$clsprty <- as.integer(as.factor(x2$clsprty))
x2$uempla <- as.integer(as.factor(x2$uempla))
x2$uempli <- as.integer(as.factor(x2$uempli))
x2$dsbld <- as.integer(as.factor(x2$dsbld))
x2$mbtru <- as.integer(as.factor(x2$mbtru))
x2$wrkctra <- as.integer(as.factor(x2$wrkctra)) 



## Coding variables that require manual effort ##
table(x2$trstprl) ## shows that we need to code this manually
levels(x2$trstprl) <- c("0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "77", "88", "99")
table(x2$trstprl) ## shows the levels as we need them
x2$trstprl <- as.integer(x2$trstprl)


levels(x2$trstplt) <- c("0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "77", "88", "99")
x2$trstplt <- as.integer(x2$trstplt)

levels(x2$trstep) <- c("0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "77", "88", "99")
x2$trstep <- as.integer(x2$trstep)

levels(x2$eisced) <- c("0", "1", "2", "3", "4", "5", "6", "7", "55", "77", "88", "99")
x2$eisced <- as.integer(x2$eisced)

levels(x2$gndr) <- c("1", "2", "9")
x2$gndr <- as.integer(x2$gndr)

levels(x2$pdjobev) <- c("1", "2", "6", "7", "8", "9")
x2$pdjobev <- as.integer(x2$pdjobev)

levels(x2$mainact) <- c("1", "2", "3", "4", "5", "6", "7", "8", "9", "66", "77", "88", "99")
x2$mainact <- as.integer(x2$mainact)

## Changing class of variables as needed for merging
class(df$essround)
class(x2$essround)

x2$essround <- as.integer(x2$essround)
x2$polintr <- as.integer(x2$polintr)
x2$trstprl <- as.integer(x2$trstprl)
x2$trstplt <- as.integer(x2$trstplt)
x2$trstep <- as.integer(x2$trstep)

## As there are only 25 variables common between these two, those are the ones we can need to merge the data. The one variable that exists in only until 2012 cannot be included in the command below otherwise it doesn't work

combined <- merge(ESSData, x2, by = c("cntry", "essround", "polintr","trstprl", "trstplt","trstep","vote","contplt","wrkprty","wrkorg","badge","sgnptit","pbldmn", "bctprd","clsprty","eisced","uempla", "uempli","dsbld", "mbtru","mainact","wrkctra","gndr","stfdem","pdjobev"), all = T)





